jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo
      - run: cd hudo && hugo
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOSHELEV_WORKS }}'
          channelId: live
          projectId: koshelev-works